export const UPDATE_ALERT = "UPDATE_ALERT";
export const WASHROOMS_FAILED = "WASHROOMS_FAILED";
export const WASHROOMS_LOADING = "WASHROOMS_LOADING";
export const WASHROOMS_SUCCEEDED = "WASHROOMS_SUCCEEDED";
export const WASHROOM_DETAIL_FAILED = "WASHROOM_DETAIL_FAILED";
export const WASHROOM_DETAIL_LOADING = "WASHROOM_DETAIL_LOADING";
export const WASHROOM_DETAIL_SUCCEEDED = "WASHROOM_DETAIL_SUCCEEDED";